# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7eb883a7c01598fa9c4a0eab407500bd58fc481915c5a0a4d293ff3eed08f488e4caa80d29d4df98fcec21522192a9ad6605e6857501f8433d0d22574ddcb8b

test:
  secret_key_base: 4e12a49952bc20181328af7d87c3f47b6eed98aa9734352c41b542c6484c0af85546e10eb6d09611cea7d935b6ead9886c136bb9464ac3d3a0559a3d67df8588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
